"""
This module defines the structure and styling for PDF reports using ReportLab.
It acts as a template for generating consistent PDF documents.
"""

from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch, cm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Image, Table, TableStyle, PageBreak
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.lib.colors import (
    black, blue, red, green, gray, lightgrey, darkgrey
)
from typing import List, Tuple, Any, Dict, Optional
from pathlib import Path

class ReportTemplate:
    """
    Defines the layout, styles, and common elements for PDF reports.
    """

    def __init__(self, output_path: Path, title: str = "Roof AI Studio Report"):
        self.output_path = output_path
        self.title = title
        self.styles = getSampleStyleSheet()
        self._setup_custom_styles()

    def _setup_custom_styles(self) -> None:
        """
        Sets up custom paragraph styles for the report.
        """
        self.styles.add(ParagraphStyle(name='TitleStyle',
                                       parent=self.styles['h1'],
                                       fontSize=24,
                                       leading=28,
                                       alignment=TA_CENTER,
                                       spaceAfter=20))
        self.styles.add(ParagraphStyle(name='Heading1',
                                       parent=self.styles['h1'],
                                       fontSize=18,
                                       leading=22,
                                       spaceBefore=12,
                                       spaceAfter=6,
                                       textColor=darkgrey))
        self.styles.add(ParagraphStyle(name='Heading2',
                                       parent=self.styles['h2'],
                                       fontSize=14,
                                       leading=18,
                                       spaceBefore=10,
                                       spaceAfter=4,
                                       textColor=gray))
        self.styles.add(ParagraphStyle(name='BodyText',
                                       parent=self.styles['Normal'],
                                       fontSize=10,
                                       leading=12,
                                       spaceBefore=6))
        self.styles.add(ParagraphStyle(name='SmallText',
                                       parent=self.styles['Normal'],
                                       fontSize=8,
                                       leading=10,
                                       textColor=gray))
        self.styles.add(ParagraphStyle(name='TableHeader',
                                       parent=self.styles['Normal'],
                                       fontSize=9,
                                       leading=11,
                                       alignment=TA_CENTER,
                                       fontName='Helvetica-Bold'))
        self.styles.add(ParagraphStyle(name='TableBody',
                                       parent=self.styles['Normal'],
                                       fontSize=9,
                                       leading=11,
                                       alignment=TA_LEFT))
        self.styles.add(ParagraphStyle(name='Footer',
                                       parent=self.styles['Normal'],
                                       fontSize=8,
                                       leading=10,
                                       alignment=TA_CENTER,
                                       textColor=gray))
        self.styles.add(ParagraphStyle(name='Signature',
                                       parent=self.styles['Normal'],
                                       fontSize=10,
                                       leading=14,
                                       spaceBefore=30))

    def _page_template(self, canvas, doc) -> None:
        """
        Defines the header and footer for each page.
        """
        canvas.saveState()
        # Header
        canvas.setFont('Helvetica-Bold', 10)
        canvas.drawString(doc.leftMargin, A4[1] - doc.topMargin + 10, self.title)
        canvas.setFont('Helvetica', 9)
        canvas.drawRightString(A4[0] - doc.rightMargin, A4[1] - doc.topMargin + 10, f"Page {doc.page}")

        # Footer
        canvas.setFont('Helvetica', 8)
        canvas.drawCentredString(A4[0] / 2.0, doc.bottomMargin / 2.0, "Generated by Roof AI Studio")
        canvas.restoreState()

    def build_document(self, story: List[Any]) -> None:
        """
        Builds the PDF document with the given story (content).

        Args:
            story (List[Any]): A list of ReportLab Flowables (Paragraph, Table, Image, etc.).
        """
        doc = SimpleDocTemplate(str(self.output_path),
                                pagesize=A4,
                                rightMargin=cm,
                                leftMargin=cm,
                                topMargin=cm * 2,
                                bottomMargin=cm * 1.5)
        doc.build(story, onFirstPage=self._page_template, onLaterPages=self._page_template)

    def get_story_elements(self, report_data: Any, company_info: Optional[Any] = None) -> List[Any]:
        """
        Generates a list of ReportLab Flowables based on the report data.
        This method should be overridden or extended by specific report types.

        Args:
            report_data (Any): The data model for the report (e.g., CustomerReport).
            company_info (Optional[Any]): Company information for branding.

        Returns:
            List[Any]: A list of ReportLab Flowables.
        """
        story: List[Any] = []

        # 1. Cover Page
        story.append(Paragraph(self.title, self.styles['TitleStyle']))
        story.append(Spacer(1, 0.5 * inch))
        if company_info and company_info.logo_path and company_info.logo_path.exists():
            try:
                logo = Image(str(company_info.logo_path), width=2*inch, height=1*inch)
                logo.hAlign = 'CENTER'
                story.append(logo)
                story.append(Spacer(1, 0.5 * inch))
            except Exception as e:
                print(f"Warning: Could not load logo image: {e}")
        story.append(Paragraph(f"Report Date: {report_data.report_date.strftime('%Y-%m-%d')}", self.styles['h2']))
        story.append(Spacer(1, 0.2 * inch))
        story.append(Paragraph(f"For: {report_data.customer_name}", self.styles['h2']))
        story.append(PageBreak())

        # 2. Customer and Project Information
        story.append(Paragraph("1. Customer & Project Information", self.styles['Heading1']))
        story.append(Paragraph(f"<b>Customer:</b> {report_data.customer_name}", self.styles['BodyText']))
        story.append(Paragraph(f"<b>Address:</b> {report_data.customer_address}", self.styles['BodyText']))
        if report_data.customer_phone:
            story.append(Paragraph(f"<b>Phone:</b> {report_data.customer_phone}", self.styles['BodyText']))
        if report_data.customer_email:
            story.append(Paragraph(f"<b>Email:</b> {report_data.customer_email}", self.styles['BodyText']))
        story.append(Spacer(1, 0.2 * inch))
        story.append(Paragraph(f"<b>Project Name:</b> {report_data.project_name}", self.styles['BodyText']))
        story.append(Paragraph(f"<b>Project Address:</b> {report_data.project_address}", self.styles['BodyText']))
        if report_data.project_description:
            story.append(Paragraph(f"<b>Description:</b> {report_data.project_description}", self.styles['BodyText']))
        story.append(PageBreak())

        # 3. Roof Analysis Summary
        story.append(Paragraph("2. Roof Analysis Summary", self.styles['Heading1']))
        story.append(Paragraph(report_data.roof_summary, self.styles['BodyText']))
        story.append(Spacer(1, 0.2 * inch))

        # 4. Roof Image
        if report_data.roof_image_path and report_data.roof_image_path.exists():
            story.append(Paragraph("Roof Image:", self.styles['Heading2']))
            try:
                img = Image(str(report_data.roof_image_path), width=6*inch) # Adjust width as needed
                img.hAlign = 'CENTER'
                story.append(img)
                story.append(Spacer(1, 0.2 * inch))
            except Exception as e:
                story.append(Paragraph(f"<i>Could not load roof image: {e}</i>", self.styles['SmallText']))

        # 5. Geometry Summary
        story.append(Paragraph("3. Geometry Summary", self.styles['Heading1']))
        if report_data.geometry_summary_text:
            story.append(Paragraph(report_data.geometry_summary_text, self.styles['BodyText']))
        if report_data.geometry_image_path and report_data.geometry_image_path.exists():
            story.append(Paragraph("Generated Geometry:", self.styles['Heading2']))
            try:
                img = Image(str(report_data.geometry_image_path), width=6*inch)
                img.hAlign = 'CENTER'
                story.append(img)
                story.append(Spacer(1, 0.2 * inch))
            except Exception as e:
                story.append(Paragraph(f"<i>Could not load geometry image: {e}</i>", self.styles['SmallText']))
        story.append(PageBreak())

        # 6. Measurements
        story.append(Paragraph("4. Measurements", self.styles['Heading1']))
        if report_data.measurements:
            data = [['Measurement', 'Value', 'Unit']]
            data.append(['Total Roof Area', f"{report_data.measurements.total_area_m2:.2f}", 'sq m'])
            data.append(['Total Perimeter', f"{report_data.measurements.total_perimeter_m:.2f}", 'm'])
            
            for plane_name, area in report_data.measurements.plane_areas_m2.items():
                data.append([f"  - {plane_name} Area", f"{area:.2f}", 'sq m'])
            for edge_name, length in report_data.measurements.edge_lengths_m.items():
                data.append([f"  - {edge_name} Length", f"{length:.2f}", 'm'])

            table = Table(data, colWidths=[3*cm, 3*cm, 2*cm])
            table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), lightgrey),
                ('TEXTCOLOR', (0, 0), (-1, 0), black),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
                ('BACKGROUND', (0, 1), (-1, -1), white),
                ('GRID', (0, 0), (-1, -1), 1, gray),
            ]))
            story.append(table)
        else:
            story.append(Paragraph("<i>No measurements available.</i>", self.styles['BodyText']))
        story.append(PageBreak())

        # 7. Material List
        story.append(Paragraph("5. Material List", self.styles['Heading1']))
        if report_data.materials_breakdown:
            data = [['Material', 'Quantity', 'Unit', 'Waste', 'Total Qty', 'Est. Cost']]
            for mat in report_data.materials_breakdown:
                data.append([
                    mat.material_name,
                    f"{mat.quantity:.2f}",
                    mat.unit.value,
                    f"{mat.waste_quantity:.2f}",
                    f"{mat.total_quantity:.2f}",
                    f"${mat.estimated_cost:.2f}"
                ])
            table = Table(data, colWidths=[4*cm, 2*cm, 1.5*cm, 1.5*cm, 2*cm, 2*cm])
            table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), lightgrey),
                ('TEXTCOLOR', (0, 0), (-1, 0), black),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
                ('BACKGROUND', (0, 1), (-1, -1), white),
                ('GRID', (0, 0), (-1, -1), 1, gray),
            ]))
            story.append(table)
        else:
            story.append(Paragraph("<i>No material breakdown available.</i>", self.styles['BodyText']))
        story.append(PageBreak())

        # 8. Price Estimate
        story.append(Paragraph("6. Price Estimate", self.styles['Heading1']))
        if report_data.estimate:
            estimate = report_data.estimate
            story.append(Paragraph(f"<b>Estimate Name:</b> {estimate.name}", self.styles['BodyText']))
            story.append(Spacer(1, 0.1 * inch))

            # Material Lines
            if estimate.material_lines:
                story.append(Paragraph("<b>Material Costs:</b>", self.styles['Heading2']))
                mat_data = [['Description', 'Qty', 'Unit Price', 'Total']]
                for line in estimate.material_lines:
                    mat_data.append([line.description, f"{line.quantity:.2f}", f"${line.unit_price:.2f}", f"${line.total_price:.2f}"])
                mat_table = Table(mat_data, colWidths=[5*cm, 2*cm, 2.5*cm, 2.5*cm])
                mat_table.setStyle(TableStyle([
                    ('BACKGROUND', (0, 0), (-1, 0), lightgrey),
                    ('TEXTCOLOR', (0, 0), (-1, 0), black),
                    ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                    ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                    ('GRID', (0, 0), (-1, -1), 1, gray),
                ]))
                story.append(mat_table)
                story.append(Spacer(1, 0.1 * inch))

            # Labor Lines
            if estimate.labor_lines:
                story.append(Paragraph("<b>Labor Costs:</b>", self.styles['Heading2']))
                lab_data = [['Description', 'Qty', 'Unit Price', 'Total']]
                for line in estimate.labor_lines:
                    lab_data.append([line.description, f"{line.quantity:.2f}", f"${line.unit_price:.2f}", f"${line.total_price:.2f}"])
                lab_table = Table(lab_data, colWidths=[5*cm, 2*cm, 2.5*cm, 2.5*cm])
                lab_table.setStyle(TableStyle([
                    ('BACKGROUND', (0, 0), (-1, 0), lightgrey),
                    ('TEXTCOLOR', (0, 0), (-1, 0), black),
                    ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                    ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                    ('GRID', (0, 0), (-1, -1), 1, gray),
                ]))
                story.append(lab_table)
                story.append(Spacer(1, 0.1 * inch))

            # Other Lines
            if estimate.other_lines:
                story.append(Paragraph("<b>Other Costs:</b>", self.styles['Heading2']))
                other_data = [['Description', 'Qty', 'Unit Price', 'Total']]
                for line in estimate.other_lines:
                    other_data.append([line.description, f"{line.quantity:.2f}", f"${line.unit_price:.2f}", f"${line.total_price:.2f}"])
                other_table = Table(other_data, colWidths=[5*cm, 2*cm, 2.5*cm, 2.5*cm])
                other_table.setStyle(TableStyle([
                    ('BACKGROUND', (0, 0), (-1, 0), lightgrey),
                    ('TEXTCOLOR', (0, 0), (-1, 0), black),
                    ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                    ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                    ('GRID', (0, 0), (-1, -1), 1, gray),
                ]))
                story.append(other_table)
                story.append(Spacer(1, 0.1 * inch))

            # Summary Table
            summary_data = [
                ['Subtotal:', f"${estimate.subtotal:.2f}"],
                ['Discount:', f"-${estimate.discount:.2f}"],
                ['Price after Discount:', f"${estimate.subtotal - estimate.discount:.2f}"],
                ['Margin:', f"{estimate.margin*100:.0f}%"],
                ['Price with Margin:', f"${(estimate.subtotal - estimate.discount) * (1 + estimate.margin):.2f}"],
                ['VAT:', f"{estimate.vat_rate*100:.0f}%"],
                ['<b>FINAL PRICE:</b>', f"<b>${estimate.final_price:.2f}</b>"]
            ]
            summary_table = Table(summary_data, colWidths=[5*cm, 5*cm])
            summary_table.setStyle(TableStyle([
                ('ALIGN', (0, 0), (-1, -1), 'RIGHT'),
                ('FONTNAME', (0, -1), (-1, -1), 'Helvetica-Bold'),
                ('BACKGROUND', (0, -1), (-1, -1), lightgrey),
                ('GRID', (0, 0), (-1, -1), 1, gray),
            ]))
            story.append(summary_table)

        else:
            story.append(Paragraph("<i>No price estimate available.</i>", self.styles['BodyText']))
        story.append(PageBreak())

        # 9. Notes
        story.append(Paragraph("7. Notes", self.styles['Heading1']))
        if report_data.notes:
            story.append(Paragraph(report_data.notes, self.styles['BodyText']))
        else:
            story.append(Paragraph("<i>No additional notes.</i>", self.styles['BodyText']))
        story.append(Spacer(1, 0.5 * inch))

        # 10. Signature Area
        story.append(Paragraph(report_data.signature_area_text, self.styles['Signature']))
        story.append(Spacer(1, 0.5 * inch))
        story.append(Paragraph("_" * 40, self.styles['Signature'])) # Line for signature
        story.append(Paragraph("Signature", self.styles['SmallText']))

        return story
